### ISSUE TITLE
Command to update `reasonRealized` of praise 

### ISSUE THREAD

**Issue by mattyg** [commons-stack/praise#436]
Hold off on this ticket until we've #435 is completed (it will likely affect this ticket)

See #435 for background.

Create a command to update all the `reasonRealized` of all praise with their human-readable formatted versions.

**Comment by kristoferlund** [comment]
Instead of merging the hack I made to get the server back online (https://github.com/commons-stack/praise/tree/fix/upgrade_issues), could we add better error handling to the current migration? Since `reasonRealized` is  not a "must have" feature, maybe it is ok it just save unprocessed `reason` as `resonRealized` if unable to fetch from discord.js. 

We should of course get to the bottom of this as well and make sure to give the bot the permissions it needs to be able to read all referenced users, channels etc. 

But btw.. what happens if I reference a channel or user that is not even on the current server? Then the bot could not possibly have access to that info.

**Comment by mattyg** [comment]
This hasn't been completed yet -- reopening.
