### ISSUE TITLE
Praising does not work in threads

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#524]

**Comment by Vyvy-vi** [comment]
It looks like this issue needs some testing to verify if there's a problem.
I just tested a local instance of praise (synced with the latest changes to main), and praising worked in threads.
<img width="704" alt="Screenshot 2022-08-19 at 1 51 06 PM" src="https://user-images.githubusercontent.com/62864373/185576746-92976fac-9b6b-4c76-b6ef-0b22929b3e66.png">

**Comment by gideonro** [comment]
![image](https://user-images.githubusercontent.com/10900268/193654920-bb682601-044c-47d2-9560-bf5771637a5b.png) Any updates on this issue? We were hoping to set up a thread for doing Sampo-specific Praise so that it doesn't clog our main channel. 

More importantly though, we want to see if there's a way to use Praise to recognize good contributions to the new TEC Curation Service. The service relies on the new Discord Forum tool (which relies on threads).

**Comment by kristoferlund** [comment]
@Vyvy-vi you mentioned today issue might be solved with upgrading to new version of discord.js, did I get that correctly? The audio quality during the call was quite noisy.

**Comment by Vyvy-vi** [comment]
Yes, it might be fixed. 
Praise is working in threads in my local build of #619, and was also working before that(since #569).
After #619 is merged and TEC's instance is updated to the latest praise version., we can test and check if praising works in threads. If it still doesn't work, we might need to debug the TEC instance separately to check what's erroring out.

**Comment by Vyvy-vi** [comment]
After attempting to debug it on the TEC instance, I found at thatTthis is a permission issue. The bot wasn't able to run `/praise` in the thread unless it had administrator permissions.

I've added the perms to the bot in TEC so praise should be usable in threads for now 👍 (though I'd recommend waiting for #619 to get merged).
