### ISSUE TITLE
Setting form saves checkboxes every time form is submitted, independent of boxes being changed or not

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#629]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/9698363/194843657-2786d158-a5d5-40e8-97ae-61cc80becdbe.png">

**Comment by kkatusic** [comment]
@kristoferlund I found what is problem:

`if (value !== setting.value) {`

value is submitted value from form, and setting.value is current setting value from database. 
This "!==" not equality and type check operator isn't good for checkbox field value, because it is provided like boolean value but database setting value is a string. 

I must figure out how to solve this problem ;)
