### ISSUE TITLE
Unable to remove quantifier role from user

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/praise#630]
[Screencast_from_10-10-22_084641.webm](https://user-images.githubusercontent.com/9698363/194881957-8729d6fd-ef2f-402e-a95d-cae33aeb2910.webm)

See video 👆, API responds with "Cannot remove quantifier currently assigned …" when it shouldn't.

**Comment by kkatusic** [comment]
I think this isn't issue, please correct me if I'm wrong. 
Check code on this link: https://github.com/commons-stack/praise/blob/main/packages/api/src/user/controllers.ts#L153

it has a comment "**If user is currently assigned to the active quantification round, and role is QUANTIFIER throw error**" and what that means if you look code below you can't remove user that is currently associated to active period.

Maybe this condition has been attached because some relations to data in the database, data that must have quantifier in some view in the application.

Users that are quantifiers and aren't attached to active period can turn off from role quantifier. Also if you haven't any active period you can turn off role quantifier from the user.

**Comment by kristoferlund** [comment]
The quantifier in the video - Mount Manu - is no longer quantifier, I guess @divine_comedian found a way to remove him. Mitch, if you remember which steps you took before being able to remove the role, please share so we can try to reproduce the issue.

**Comment by kkatusic** [comment]
@kristoferlund ask Mitch this: Did Mount Manu was a quantifier and removed in the meantime at the Round 19 period?

**Comment by kristoferlund** [comment]
We were unable to reproduce this issue. Closing for now.
